module.exports =
  hygienist: require 'hygienist-middleware'
  escapist: require 'escapist-middleware'
  archivist: require 'archivist-middleware'
  alchemist: require 'alchemist-middleware'
  apologist: require 'apology-middleware'
  publicist: require 'publicist-middleware'
  columnist: require 'morgan'
  pathologist: require 'pathologist-middleware'
  journalist: require 'infestor'
  minimist: require 'compression'
  egoist: require 'serve-favicon'
